package:
  name: chembl_webresource_client
  version: 0.9.31

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python {{ python }}

  run:
    - python  {{ python }}
    - urllib3
    - requests
    - requests-cache
    - grequests
    - easydict
    - gevent
    - gevent-openssl
    - unittest2six

about:
  home: https://github.com/chembl/chembl_webresource_client
  license: https://github.com/chembl/chembl_webresource_client/blob/master/LICENSE
  summary: ""
  description: |
    This is a copy from https://github.com/chembl/chembl_webresource_client to be installed with python 3.6 and 3.7.
